### ISSUE TITLE
[QA] 마지막 버그 수정

### ISSUE THREAD

**Issue by SongSeoYoung** [mash-up-kr/mobalmobal_iOS#143]
- [ ] 도네이션 생성 시 디데이 문제. 아래 두 이미지는 왼쪽부터 종료일자 0507, 0508인데 둘 다 D-1
<img src="https://user-images.githubusercontent.com/42825223/117247970-28484480-ae7a-11eb-94a1-2b7d32ad8879.png" width=200> <img src="https://user-images.githubusercontent.com/42825223/117247986-2c746200-ae7a-11eb-8fc8-82497c4d24ec.png" width=200>
- [x] 도네이션 생성 시 티끌모아 글씨 삭제 필요
- [x] 도네이션 생성 시 너무 큰 사이즈의 이미지 alert처리
- [x] 도네이션 생성 시 내 도네이션으로 분류되어지지않음. user_id는 일치하나 백엔드에서 내려오는 값 부터 내 도네이션으로 분류가 안되는 것 같음. feature/seoyoungQA. hofix/signup 에서는 됨
- [x] 잔액부족, 내 도네이션 후원금지 주석처리 후 내 도네이션에 후원시 이미지 변화하는지 체크필요!!!
- [ ] 도네이션 상세페이지에서 후원하기->직접입력->후원완료->도네이션상세로 넘어갈 때 뷰 자체 업데이트가안됨
- [x] navigation bar 타이틀 위치가 좀 이상한거같은데..?
<img src="https://user-images.githubusercontent.com/42825223/117245137-4b242a00-ae75-11eb-91fc-2a9a731bd233.png" width=200>

- [x]  D-1 인데 progress bar가 10000%로 차고 있음.
<img width="350" alt="스크린샷 2021-05-06 오후 9 14 01" src="https://user-images.githubusercontent.com/48345308/117296422-feaa1000-aeaf-11eb-8890-90f247c7a661.png">

**Comment by tngusmiso** [comment]
>  도네이션 상세페이지에서 후원하기->직접입력->후원완료->도네이션상세로 넘어갈 때 뷰 자체 업데이트가안됨

제가 직접입력에는 추가하지 않았네요ㅠㅠ 이거 해결하셨나요??

`DonationDetailViewController.swift`의 `presentDonateMoneyVC()`를 보면 
```swift
donateMoneyVC.donationCompletionHander = { [weak self] in
    self?.viewModel.callDonationInfoAPI()
}
```
이 부분이 있습니다.
`donateMoneyVC` 로 넘어갈 때 donationCompletionHandler라는 클로저를 함께 넘겨주고,
후원 성공 시, `donationCompletionHandler`를 실행시키도록 구현했습니다.

마찬가지로 InputDonationMoneyViewController로 넘어갈 때 donationCompletionHandler를 넘겨주고,
DonateCompleteViewController로 넘어갈 때도 마찬가지로 donationCompletionHandler를 넘겨주면 될 것 같습니당

**Comment by SongSeoYoung** [comment]
> > 도네이션 상세페이지에서 후원하기->직접입력->후원완료->도네이션상세로 넘어갈 때 뷰 자체 업데이트가안됨
> 
> 제가 직접입력에는 추가하지 않았네요ㅠㅠ 이거 해결하셨나요??
> 
> `DonationDetailViewController.swift`의 `presentDonateMoneyVC()`를 보면
> 
> ```swift
> donateMoneyVC.donationCompletionHander = { [weak self] in
>     self?.viewModel.callDonationInfoAPI()
> }
> ```
> 
> 이 부분이 있습니다.
> `donateMoneyVC` 로 넘어갈 때 donationCompletionHandler라는 클로저를 함께 넘겨주고,
> 후원 성공 시, `donationCompletionHandler`를 실행시키도록 구현했습니다.
> 
> 마찬가지로 InputDonationMoneyViewController로 넘어갈 때 donationCompletionHandler를 넘겨주고,
> DonateCompleteViewController로 넘어갈 때도 마찬가지로 donationCompletionHandler를 넘겨주면 될 것 같습니당

그런데 이렇게하려면 뷰가 뷰를 참조해야하거나 하나의 뷰에 두개의 viewModel을 가지고있어야할 것 같은데.. 그렇게해도되나요?

InputDonationMoneyViewController로 넘어가는게 DonationDetailViewController에있는게 아니라 DonateMoneyViewController에있어서.. 
 ```swift
 donateMoneyVC.donationCompletionHander = { [weak self] in
     self?.viewModel.callDonationInfoAPI()
 }
```
여기 DonationDetailViewController 에있는 viewModel이랑 DonateMoneyViewController에있는 ViewModel이 다릅니다ㅠㅠ 

제가 뭘 놓치고있는건지 모르겠네여ㅠ

**Comment by tngusmiso** [comment]
donation detail은 상세정보 받아오는 친구고
donate money는 후원하는 친구라서 그럽니다!

InputDonationMoneyViewController.completionHandler = completionHandler 
이런식으로 넘겨주면 되는데 이부분 제가 할까용?!
